# Generated by Django 4.1.7 on 2023-02-18 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('composer', models.CharField(blank=True, max_length=100, null=True)),
                ('key', models.CharField(blank=True, max_length=15, null=True)),
                ('feel', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserTune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playonpiano', models.BooleanField(default=False)),
                ('playonjamsession', models.BooleanField(default=False)),
                ('playonstage', models.BooleanField(default=False)),
                ('havesheet', models.BooleanField(default=False)),
                ('sheet', models.FileField(blank=True, null=True, upload_to='')),
                ('updated', models.DateField(auto_now=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('tune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tunes.tune')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
