# Generated by Django 4.1.7 on 2023-02-18 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunes', '0002_feel_key'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feel',
            new_name='Genre',
        ),
        migrations.RenameField(
            model_name='tune',
            old_name='feel',
            new_name='genre',
        ),
    ]
