# Generated by Django 4.1.7 on 2023-02-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunes', '0003_rename_feel_genre_rename_feel_tune_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertune',
            name='sheet',
            field=models.FileField(blank=True, null=True, upload_to='tunes/'),
        ),
    ]
