# Generated by Django 4.1.7 on 2023-02-20 09:42

from django.db import migrations, models
import tunes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tunes', '0005_alter_usertune_sheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertune',
            name='sheet',
            field=models.FileField(blank=True, null=True, upload_to='tunes/None', validators=[tunes.validators.validate_file_extension]),
        ),
    ]
