# Generated by Django 4.1.7 on 2023-02-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunes', '0009_alter_usertune_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertune',
            name='notes',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
