# Generated by Django 4.1.7 on 2023-03-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunes', '0011_alter_usertune_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertune',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
