# Generated by Django 4.1.7 on 2023-03-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunes', '0012_usertune_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tune',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
