# Generated by Django 4.1.7 on 2023-03-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunes', '0013_alter_tune_genre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Key',
        ),
        migrations.AlterField(
            model_name='tune',
            name='key',
            field=models.CharField(blank=True, choices=[('C maj', 'C maj'), ('G maj', 'G maj'), ('D maj', 'D maj'), ('A maj', 'A maj'), ('E maj', 'E maj'), ('F maj', 'F maj'), ('B maj', 'B maj'), ('Cb maj', 'Cb maj'), ('Gb maj', 'Gb maj'), ('F# maj', 'F# maj'), ('Db maj', 'Db maj'), ('C# maj', 'C# maj'), ('Ab maj', 'Ab maj'), ('Eb maj', 'Eb maj'), ('Bb maj', 'Bb maj')], max_length=15, null=True),
        ),
    ]
