# Generated by Django 4.1.7 on 2023-04-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunes', '0017_usertunelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertune',
            name='lyrics',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
