# Generated by Django 4.1.7 on 2023-04-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunes', '0018_usertune_lyrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertune',
            name='lyrics',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
