# Generated by Django 4.1.7 on 2023-04-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunes', '0019_alter_usertune_lyrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertunelist',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
