# Generated by Django 4.1.7 on 2023-04-22 12:58

from django.db import migrations, models
import tunes.models
import tunes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tunes', '0021_alter_usertunelist_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertune',
            name='sheet',
            field=models.FileField(blank=True, null=True, upload_to=tunes.models.tunes_user_directory_path, validators=[tunes.validators.validate_file_extension, tunes.validators.validate_file_size]),
        ),
    ]
